default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: rails_app_development

test:
  <<: *default
  database: rails_app_test

production:
  primary: &primary_production
    <<: *default
    database: rails_app_production
    username: rails_app
    password: <%= ENV["RAILS_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_app_production_queue
    migrations_paths: db/queue_migrate
